# Describes the format for available services for audiconnect

refresh_vehicle_data:
  fields:
    vin:
      required: true
      selector:
        device:
          integration: audiconnect

execute_vehicle_action:
  fields:
    vin:
      required: true
      selector:
        device:
          integration: audiconnect
    action:
      required: true
      selector:
        select:
          translation_key: select_mode
          options:
            - lock
            - unlock
            - start_climatisation
            - stop_climatisation
            - start_charger
            - start_timed_charger
            - stop_charger
            - start_preheater
            - stop_preheater
            - start_window_heating
            - stop_window_heating
