# Describes the format for available services for audiconnect

refresh_vehicle_data:
  name: Refresh vehicle data
  description: >
    Request an update of the state from the vehicle, as opposed to the normal
    update mechanism, which only retrieves data from the servers.
  fields:
    vin:
      name: VIN
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: WBANXXXXXX1234567

execute_vehicle_action:
  name: Execute Vehicle Action
  description: >
    Execute Vehicle actions
  fields:
    vin:
      name: VIN
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: WBANXXXXXX1234567
    action:
      name: Action
      description: >
        The action to be executed. Possible choices, depending on subscription
        options, include 'lock', 'unlock', 'start_climatisation',
        'stop_climatisation, 'start_charger', 'start_timed_charger',
        'stop_charger', 'start_preheater', 'stop_preheater,
        'start_window_heating', 'stop_window_heating'
      example: lock

update_all_vehicles_data:
  name: Update All Vehicles Data
  description: >
    Updates vehicle data, for all vehicles, from the online source
    without forcing a vehicle refresh. If the vehicle has not
    recently updated its data, the information retrieved may still
    be outdated. Vehicle data typically refreshes after receiving
    a command, such as starting climate control. It's recommended
    to wait approximately 30 seconds between initiating a command
    and using this service call to ensure updated data is fetched.
    This is essentially the same function as restarting the
    integration.
