# Describes the format for available services for audiconnect

refresh_data:
  name: Refresh vehicle data
  description: >
    Request an update of the state from the vehicle, as opposed to the normal
    update mechanism, which only retrieves data from the servers.
  fields:
    vin:
      required: true
      name: VIN
      description: >
        The Vehicle Identification Number (VIN) of the Audi vehicle. This should be a 17-character identifier unique to each vehicle.
      example: "WAUZZZ4G7EN123456"
      selector:
        text:

execute_vehicle_action:
  name: Execute Vehicle Action
  description: >
    Perform various actions on the vehicle, such as locking, unlocking, managing climatisation, and charging. The action to be performed is specified along with necessary parameters.
  fields:
    vin:
      required: true
      name: VIN
      description: >
        The Vehicle Identification Number (VIN) of the Audi vehicle. This should be a 17-character identifier unique to each vehicle.
      example: "WAUZZZ4G7EN123456"
      selector:
        text:
    action:
      required: true
      name: Action
      description: >
        The specific action to perform on the vehicle. Note that available actions may vary based on the vehicle's capabilities.
      example: "start_climatisation"
      selector:
        select:
          translation_key: select_mode
          options:
            - lock
            - unlock
            - start_climatisation
            - stop_climatisation
            - start_charger
            - start_timed_charger
            - stop_charger
            - start_preheater
            - stop_preheater
            - start_window_heating
            - stop_window_heating
    temp_f:
      name: Temperature (Fahrenheit)
      description: >
        (Optional, for 'start_climatisation' action) Desired climatisation temperature in degrees Fahrenheit. If provided, this takes precedence over 'temp_c'. If nothing is provided, the temperature will be set to 70°F.
      selector:
        number:
          min: 60
          max: 80
    temp_c:
      name: Temperature (Celsius)
      description: >
        (Optional, for 'start_climatisation' action) Desired climatisation temperature in degrees Celsius. This is used if 'temp_f' is not provided. If nothing is provided, the temperature will be set to 21°C.
      selector:
        number:
          min: 15
          max: 27
    glass_heating:
      name: Glass Heating
      description: >
        (Optional, for 'start_climatisation' action) Enable or disable glass heating. Setting this to True activates glass heating.
      selector:
        boolean:
    seat_fl:
      name: Front-Left Seat Comfort
      description: >
        (Optional, for 'start_climatisation' action) Enable or disable Auto Seat Comfort for the front-left seat. Setting this to true activates the Auto Seat Comfort.
      selector:
        boolean:
    seat_fr:
      name: Front-Right Seat Comfort
      description: >
        (Optional, for 'start_climatisation' action) Enable or disable Auto Seat Comfort for the front-right seat. Setting this to true activates the Auto Seat Comfort.
      selector:
        boolean:
    seat_rl:
      name: Rear-Left Seat Comfort
      description: >
        (Optional, for 'start_climatisation' action) Enable or disable Auto Seat Comfort for the rear-left seat. This is particularly useful in vehicles equipped with rear seat comfort options.
      selector:
        boolean:
    seat_rr:
      name: Rear-Right Seat Comfort
      description: >
        (Optional, for 'start_climatisation' action) Enable or disable Auto Seat Comfort for the rear-right seat. This is particularly useful in vehicles equipped with rear seat comfort options.
      selector:
        boolean:

