# Describes the format for available services for audiconnect
---
refresh_data:
  name: Refresh Vehicle Data
  description: >
    Request an update of the state from the vehicle, as opposed to the normal
    update mechanism, which only retrieves data from the servers.
  fields:
    vin:
      required: true
      name: VIN
      description: >
        The Vehicle Identification Number (VIN) of the Audi vehicle.
        This should be a 17-character identifier unique to each vehicle.
      example: "WAUZZZ4G7EN123456"
      selector:
        text:

execute_vehicle_action:
  name: Execute Vehicle Action
  description: >
    Perform various actions on the vehicle.
  fields:
    vin:
      required: true
      name: VIN
      description: >
        The Vehicle Identification Number (VIN) of the Audi vehicle. 
        This should be a 17-character identifier unique to each vehicle.
      example: "WAUZZZ4G7EN123456"
      selector:
        text:
    action:
      required: true
      name: Action
      description: >
        The specific action to perform on the vehicle.
        Note that available actions may vary based on the vehicle's capabilities.
      example: "start_climatisation"
      selector:
        select:
          options:
            - label: Lock
              value: lock
            - label: Unlock
              value: unlock
            - label: Start Climatisation
              value: start_climatisation
            - label: Stop Climatisation
              value: stop_climatisation
            - label: Start Charger
              value: start_charger
            - label: Start Timed Charger
              value: start_timed_charger
            - label: Stop Charger
              value: stop_charger
            - label: Start Preheater
              value: start_preheater
            - label: Stop Preheater
              value: stop_preheater
            - label: Start Window Heating
              value: start_window_heating
            - label: Stop Window Heating
              value: stop_window_heating
    temp_f:
      name: Temperature (Fahrenheit)
      description: >
        (Optional) For 'start_climatisation': 
        Set temperature in 째F. Defaults to 70째F if not provided. 
        Overrides 'temp_c'.
      selector:
        number:
          min: 60
          max: 80
    temp_c:
      name: Temperature (Celsius)
      description: >
        (Optional) For 'start_climatisation': 
        Set temperature in 째C. Defaults to 21째C if not provided. 
        Overridden if 'temp_f' is provided.
      selector:
        number:
          min: 15
          max: 27
    glass_heating:
      name: Glass Heating
      description: >
        (Optional) For 'start_climatisation':
        Enable or disable glass heating. Setting this to True activates glass heating.
      selector:
        boolean:
    seat_fl:
      name: Front-Left Seat Comfort
      description: >
        (Optional) For 'start_climatisation':
        Enable or disable Auto Seat Comfort for the front-left seat. 
        Setting this to true activates the Auto Seat Comfort.
      selector:
        boolean:
    seat_fr:
      name: Front-Right Seat Comfort
      description: >
        (Optional) For 'start_climatisation':
        Enable or disable Auto Seat Comfort for the front-right seat. 
        Setting this to true activates the Auto Seat Comfort.
      selector:
        boolean:
    seat_rl:
      name: Rear-Left Seat Comfort
      description: >
        (Optional) For 'start_climatisation':
        Enable or disable Auto Seat Comfort for the rear-left seat. 
        This is particularly useful in vehicles equipped with rear seat comfort options.
      selector:
        boolean:
    seat_rr:
      name: Rear-Right Seat Comfort
      description: >
        (Optional) For 'start_climatisation':
        Enable or disable Auto Seat Comfort for the rear-right seat. 
        This is particularly useful in vehicles equipped with rear seat comfort options.
      selector:
        boolean:
